import { request } from "../ai";
import type { LFAI } from "./typings";

/** Stream a chat message Send a message to ARIA-7 and receive a streaming response using Vercel AI SDK data stream protocol POST /api/v1/chat */
export async function chat(body: LFAI.ChatRequestDto,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/chat', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Clear conversation history Delete all conversation messages for the authenticated user DELETE /api/v1/chat */
export async function clearConversation(
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/chat', {
  method: 'DELETE',
    ...(options || {}),
  });
}

/** Get conversation history Retrieve paginated conversation history for the authenticated user GET /api/v1/chat/history */
export async function getHistory(
  // Param type generated by superposition
  params: LFAI.getHistoryParams
    ,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/chat/history', {
  method: 'GET',
    params: {
        ...params,},
    ...(options || {}),
  });
}

