import { request } from "../ai";
import type { LFAI } from "./typings";

/** Report a user activity Log a user-initiated activity event from the frontend application POST /api/v1/activities */
export async function reportActivity(body: LFAI.ReportActivityDto,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/activities', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Submit user feedback Submit feedback or suggestions from the user POST /api/v1/feedback */
export async function submitFeedback(body: LFAI.SubmitFeedbackDto,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/feedback', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Get paginated activity timeline Retrieve user's activity timeline with pagination support GET /api/v1/timeline */
export async function getTimeline(
  // Param type generated by superposition
  params: LFAI.getTimelineParams
    ,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/timeline', {
  method: 'GET',
    params: {

        ...params,},
    ...(options || {}),
  });
}

/** Get unread AI activity count in the timeline GET /api/v1/timeline/unread */
export async function getUnreadTimeline(
  options?: { [key: string]: any }
) {
  return request<{ count: number }>('/api/v1/timeline/unread', {
    method: 'GET',
    ...(options || {}),
  });
}

/** Mark timeline as seen POST /api/v1/timeline/mark-seen */
export async function markTimelineSeen(
  options?: { [key: string]: any }
) {
  return request<{ seen: true }>('/api/v1/timeline/mark-seen', {
    method: 'POST',
    ...(options || {}),
  });
}

/** SSE stream for real-time timeline events Establish Server-Sent Events connection for real-time activity updates GET /api/v1/timeline/stream */
export async function streamTimeline(
  options ?: {[key: string]: any}
) {
  return request<LFAI>('/api/v1/timeline/stream', {
  method: 'GET',
    ...(options || {}),
  });
}

