import { request } from "../services"
import type { LFAI } from "./typings";

/** Report a user activity Log a user-initiated activity event from the frontend application POST /api/v1/activities */
export async function reportActivity(body: LFAI.ReportActivityDto,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/activities', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Submit user feedback Submit feedback or suggestions from the user POST /api/v1/feedback */
export async function submitFeedback(body: LFAI.SubmitFeedbackDto,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/feedback', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Get paginated activity timeline Retrieve user's activity timeline with pagination support GET /api/v1/timeline */
export async function getTimeline(
  // Param type generated by superposition
  params: LFAI.getTimelineParams
    ,
  options ?: {[key: string]: any}
) {
  return request<any>('/api/v1/timeline', {
  method: 'GET',
    params: {
        
        ...params,},
    ...(options || {}),
  });
}

/** SSE stream for real-time timeline events Establish Server-Sent Events connection for real-time activity updates GET /api/v1/timeline/stream */
export async function streamTimeline(
  options ?: {[key: string]: any}
) {
  return request<LFAI>('/api/v1/timeline/stream', {
  method: 'GET',
    ...(options || {}),
  });
}

