import { request } from "../services";
import type { LF } from "./typings";

/** Get all subtasks Retrieves all subtasks for the specified task GET /api/v1/tasks/${param0}/subtasks */
export async function subtasksControllerFindAll(
  // Param type generated by superposition
  params: LF.SubtasksControllerFindAllParams,
  options?: { [key: string]: any }
) {
  const { taskId: param0, ...queryParams } = params;
  return request<LF.SubtaskEntity[]>(`/api/v1/tasks/${param0}/subtasks`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Create a new subtask Creates a new subtask for the specified task POST /api/v1/tasks/${param0}/subtasks */
export async function subtasksControllerCreate(
  // Param type generated by superposition
  params: LF.SubtasksControllerCreateParams,
  body: LF.CreateSubtaskDto,
  options?: { [key: string]: any }
) {
  const { taskId: param0, ...queryParams } = params;
  return request<LF.SubtaskEntity>(`/api/v1/tasks/${param0}/subtasks`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Get subtask by ID Retrieves a specific subtask by its ID GET /api/v1/tasks/${param1}/subtasks/${param0} */
export async function subtasksControllerFindOne(
  // Param type generated by superposition
  params: LF.SubtasksControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, taskId: param1, ...queryParams } = params;
  return request<LF.SubtaskEntity>(
    `/api/v1/tasks/${param1}/subtasks/${param0}`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}

/** Delete subtask Deletes a specific subtask by its ID DELETE /api/v1/tasks/${param1}/subtasks/${param0} */
export async function subtasksControllerRemove(
  // Param type generated by superposition
  params: LF.SubtasksControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, taskId: param1, ...queryParams } = params;
  return request<any>(`/api/v1/tasks/${param1}/subtasks/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Update subtask Updates a specific subtask by its ID PATCH /api/v1/tasks/${param1}/subtasks/${param0} */
export async function subtasksControllerUpdate(
  // Param type generated by superposition
  params: LF.SubtasksControllerUpdateParams,
  body: LF.UpdateSubtaskDto,
  options?: { [key: string]: any }
) {
  const { id: param0, taskId: param1, ...queryParams } = params;
  return request<LF.SubtaskEntity>(
    `/api/v1/tasks/${param1}/subtasks/${param0}`,
    {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
      },
      params: { ...queryParams },
      data: body,
      ...(options || {}),
    }
  );
}
