import { request } from "../core"
import type { LF } from "./typings";

/** Get all tasks Retrieves paginated list of tasks for the authenticated user GET /api/v1/tasks */
export async function tasksControllerFindAll(
  // Param type generated by superposition
  params: LF.TasksControllerFindAllParams
    ,
  options ?: {[key: string]: any}
) {
  return request<LF.PaginatedTasksEntity>('/api/v1/tasks', {
  method: 'GET',
    params: {
        // limit has a default value: 20
          'limit': '20',
        
        ...params,},
    ...(options || {}),
  });
}

/** Create a new task Creates a new task for the authenticated user POST /api/v1/tasks */
export async function tasksControllerCreate(body: LF.CreateTaskDto,
  options ?: {[key: string]: any}
) {
  return request<LF.TaskEntity>('/api/v1/tasks', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Get task by ID Retrieves a specific task by its ID for the authenticated user GET /api/v1/tasks/${param0} */
export async function tasksControllerFindOne(
  // Param type generated by superposition
  params: LF.TasksControllerFindOneParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.TaskEntity>(`/api/v1/tasks/${param0}`, {
  method: 'GET',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** Delete task Deletes a specific task by its ID for the authenticated user DELETE /api/v1/tasks/${param0} */
export async function tasksControllerRemove(
  // Param type generated by superposition
  params: LF.TasksControllerRemoveParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<any>(`/api/v1/tasks/${param0}`, {
  method: 'DELETE',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** Update task Updates a specific task by its ID for the authenticated user PATCH /api/v1/tasks/${param0} */
export async function tasksControllerUpdate(
  // Param type generated by superposition
  params: LF.TasksControllerUpdateParams
    ,body: LF.UpdateTaskDto,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.TaskEntity>(`/api/v1/tasks/${param0}`, {
  method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
    },
    params: {...queryParams,},
    data: body,
    ...(options || {}),
  });
}

