import { request } from "../services"
import type { LF } from "./typings";

/** [Admin] Get all tasks Retrieves all tasks from all users (admin only) GET /api/v1/users/admin/tasks */
export async function usersControllerFindAllTasks(
  options ?: {[key: string]: any}
) {
  return request<LF.PaginatedTasksEntity>('/api/v1/users/admin/tasks', {
  method: 'GET',
    ...(options || {}),
  });
}

/** [Admin] Delete any task Deletes any task from any user (admin only) DELETE /api/v1/users/admin/tasks/${param0} */
export async function usersControllerDeleteTask(
  // Param type generated by superposition
  params: LF.UsersControllerDeleteTaskParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<any>(`/api/v1/users/admin/tasks/${param0}`, {
  method: 'DELETE',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** [Admin] Update any task Updates any task from any user (admin only) PATCH /api/v1/users/admin/tasks/${param0} */
export async function usersControllerUpdateTask(
  // Param type generated by superposition
  params: LF.UsersControllerUpdateTaskParams
    ,body: LF.UpdateTaskDto,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.TaskEntity>(`/api/v1/users/admin/tasks/${param0}`, {
  method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
    },
    params: {...queryParams,},
    data: body,
    ...(options || {}),
  });
}

/** Get current user Returns the authenticated user information from JWT token GET /api/v1/users/me */
export async function usersControllerGetMe(
  options ?: {[key: string]: any}
) {
  return request<LF.UserEntity>('/api/v1/users/me', {
  method: 'GET',
    ...(options || {}),
  });
}

