import { request } from "../services"
import type { LF } from "./typings";

/** List webhook subscriptions Get all webhook subscriptions for the authenticated user GET /api/v1/webhooks/subscriptions */
export async function webhooksControllerFindAll(
  options ?: {[key: string]: any}
) {
  return request<LF.WebhookSubscriptionEntity[]>('/api/v1/webhooks/subscriptions', {
  method: 'GET',
    ...(options || {}),
  });
}

/** Create webhook subscription Register a new webhook endpoint to receive event notifications POST /api/v1/webhooks/subscriptions */
export async function webhooksControllerCreate(body: LF.CreateWebhookSubscriptionDto,
  options ?: {[key: string]: any}
) {
  return request<LF.WebhookSubscriptionEntity>('/api/v1/webhooks/subscriptions', {
  method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Get webhook subscription Get a specific webhook subscription by ID GET /api/v1/webhooks/subscriptions/${param0} */
export async function webhooksControllerFindOne(
  // Param type generated by superposition
  params: LF.WebhooksControllerFindOneParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.WebhookSubscriptionEntity>(`/api/v1/webhooks/subscriptions/${param0}`, {
  method: 'GET',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** Delete webhook subscription Delete a specific webhook subscription DELETE /api/v1/webhooks/subscriptions/${param0} */
export async function webhooksControllerRemove(
  // Param type generated by superposition
  params: LF.WebhooksControllerRemoveParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<any>(`/api/v1/webhooks/subscriptions/${param0}`, {
  method: 'DELETE',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** Update webhook subscription Update a specific webhook subscription PATCH /api/v1/webhooks/subscriptions/${param0} */
export async function webhooksControllerUpdate(
  // Param type generated by superposition
  params: LF.WebhooksControllerUpdateParams
    ,body: LF.UpdateWebhookSubscriptionDto,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.WebhookSubscriptionEntity>(`/api/v1/webhooks/subscriptions/${param0}`, {
  method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
    },
    params: {...queryParams,},
    data: body,
    ...(options || {}),
  });
}

/** List webhook deliveries Get recent delivery history for a subscription GET /api/v1/webhooks/subscriptions/${param0}/deliveries */
export async function webhooksControllerGetDeliveries(
  // Param type generated by superposition
  params: LF.WebhooksControllerGetDeliveriesParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.WebhookDeliveryEntity[]>(`/api/v1/webhooks/subscriptions/${param0}/deliveries`, {
  method: 'GET',
    params: {...queryParams,},
    ...(options || {}),
  });
}

/** Test webhook Send a test event to the webhook endpoint POST /api/v1/webhooks/subscriptions/${param0}/test */
export async function webhooksControllerTest(
  // Param type generated by superposition
  params: LF.WebhooksControllerTestParams
    ,
  options ?: {[key: string]: any}
) {
  const { 'id': param0, 
  ...queryParams
  } = params;
  return request<LF.WebhookDeliveryEntity>(`/api/v1/webhooks/subscriptions/${param0}/test`, {
  method: 'POST',
    params: {...queryParams,},
    ...(options || {}),
  });
}

